zh/_blog.yml
zh/how-to-generate.md

add how-to-generate cn version

---

zh/_blog.yml
zh/fine-tune-whisper.md

fine-tune-whisper cn done

---

zh/_blog.yml
zh/mms_adapters.md
zh/policy-ntia-rfc.md

add mms_adapters and policy

---

zh/stacklamma.md
zh/train-optimize-sd-intel.md

There are some little questions left to be , maybe edit further.

Translate train-optimize-sd-intel.md to zh

---

zh/diffusers-turns-1

translate diffusers-turns-1

---

zh/_blog.yml
zh/os-llms.md

translation of os-llms.md

---

zh/_blog.yml
zh/encrypted-llm.md
zh/t2i-sdxl-adapters.md

t2i-sdxl-adapters cn done

---

zh/_blog.yml
zh/audioldm2.md
zh/bridgetower.md
zh/t2i-sdxl-adapters.md

1. update bridgetower for new added content
2. audioldm2 cn done
@zhongdongy , pls help review.

bridgetower and audioldm2

---

zh/_blog.yml
zh/audioldm2.md
zh/bridgetower.md
zh/the-age-of-ml-as-code.md

the-age-of-ml-as-code cn done

---

zh/_blog.yml
zh/trl-ddpo.md

trl-ddpo cn done

---

zh/_blog.yml
zh/long-range-transformers.md

@zhongdongy , pls help review. Thx.

long-range-transformers cn done

---

zh/4bit-transformers-bitsandbytes.md
zh/_blog.yml
zh/long-range-transformers.md

4bit-transformers-bitsandbytes cn done

---

zh/_blog.yml
zh/big-bird.md
zh/pytorch-fsdp.md
zh/ram-efficient-pytorch-fsdp.md

ram-efficient-pytorch-fsdp cn done

---

zh/Lora-for-sequence-classification-with-Roberta-Llama-Mistral.md
zh/_blog.yml
zh/ram-efficient-pytorch-fsdp.md

Lora-for-sequence-classification-with-Roberta-Llama-Mistral cn done

---

zh/_blog.yml
zh/moe.md

@zhongdongy ,pls help review, thx.
related PR [add zh/moe.md](https://github.com/huggingface/blog/pull/1712)

add zh/moe.md

---

zh/_blog.yml
zh/sdxl_lora_advanced_script.md

sdxl_lora_advanced_script cn done

---

zh/_blog.yml
zh/open-source-llms-as-agents.md
zh/sdxl_lora_advanced_script.md

add open-source-llms-as-agents

add open-source-llms-as-agents

---

zh/_blog.yml
zh/watermarking.md

Add zh translation for watermarking.md

---

zh/_blog.yml
zh/community-datasets.md

community-datasets cn done

---

zh/_blog.yml
zh/train-dgx-cloud.md

Should wait for the yml validator test for the `_blog.yml` file.

Add zh/ translation for train-dgx-cloud.md

---

zh/_blog.yml
zh/noob_intro_transformers.md

noob_intro_transformers cn done

---

zh/_blog.yml
zh/setfit-optimum-intel.md
zh/vlms.md

vlms cn done

---

zh/Jack of All Trades, Master of Some, a Multi-Purpose Transformer Agent.md
zh/_blog.yml
zh/hugging-face-wiz-security-blog.md
zh/sc2-instruct.md

https://huggingface.co/blog/jat
https://huggingface.co/blog/hugging-face-wiz-security-blog
translations.

Blog translation

---

zh/_blog.yml
zh/asr-diarization.md

asr-diarization cn done

---

zh/_blog.yml
zh/putting_rl_back_in_rlhf_with_rloo.md

update RLOO zh

---

zh/_blog.yml
zh/beating-gaia.md

translate the blog ,Our Transformers Code Agent beats the GAIA benchmark! , to chinese
@zhongdongy

update gaia zh

---

zh/_blog.yml
zh/finetune-florence2.md

finetune-florence2 zh done

---

zh/_blog.yml
zh/intel-protein-language-model-protst.md

@zhongdongy, pls help review, thx.

intel-protein-language-model-protst zh done

---

zh/_blog.yml
zh/quanto-diffusers.md

quanto-diffusers zh done

---

zh/_blog.yml
zh/packing-with-FA2.md

update cn packing-with-FA2

---

zh/_blog.yml
zh/designing-positional-encoding.md

add zh/designing-positional-encoding.md
